### ISSUE TITLE
Updating Kendra logo/name/URL?

### ISSUE THREAD

**Issue by dahacouk** [bitmindco/ovn-space#3]
Hi @dgrmunch

Thanks for the credentials! Thanks so much for adding Kendra in! I'm a [Drupal](https://www.drupal.org) person myself and not good with WordPress. I cannot figure out how to update the Kendra logo/name/URL (permissions?). Would it be possible to quickly update these 4 issues? 
- [x] The dropdown wording for Kendra Initiative is fine!
- [x] Can we use the Kendra Initiative logo at https://avatars2.githubusercontent.com/u/275532 instead?
- [x] Can we change the organisation title from KENDRA to KENDRA INITIATIVE ?
- [x] Can we change the URL from http://www.kendra.org.uk/ to www.kendra.io ? To point to new website and be consistent with other URLs that don't display "http://" at the start.
- [x] Can we use the Twitter account https://twitter.com/kendraio ?

Many thanks in advance. I'll leave you alone for a month for sure after this! :smile: 

Cheers Daniel

**Comment by dgrmunch** [comment]
Sure! I will do it this friday if it is ok.
Excuse me, I did it fast! I am out of time and now completly full of work
:-)

On Wednesday, 21 October 2015, Daniel Harris notifications@github.com
wrote:

> Hi Diego,
> 
> Thanks for the credentials! Thanks so much for adding Kendra in! I'm a
> Drupal https://www.drupal.org person myself and not good with
> WordPress. I cannot figure out how to update the Kendra logo/name/URL
> (permissions?). Would it be possible to quickly update these 4 issues?
> - The dropdown wording for Kendra Initiative is fine!
> - Can we use the Kendra Initiative logo at
>   https://avatars2.githubusercontent.com/u/275532 instead?
> - Can we change the organisation title from KENDRA to KENDRA
>   INITIATIVE ?
> - Can we change the URL from http://www.kendra.org.uk/ to www.kendra.io
>   ? To point to new website and be consistent with other URLs that don't
>   display "http://" at the start.
> - Can we use the Twitter account https://twitter.com/kendraio ?
> 
> Many thanks in advance. I'll leave you alone for a month for sure after
> this! [image: :smile:]
> 
> Cheers Daniel
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bitmindco/ovn-space/issues/3.

## 

_Diego González Rodríguez_
Phone*: *(0034) 625899119
Email: xmunch@xmunch.com
Personal web: http://www.xmunch.com

_Bitcoin:_ 1JLg3M9H2xS4qbZEkRkvY8eeSDAVW1kho8
_Litecoin: \* LPRt76XYmvGK3i73z9dBYHBBnhTS656UTs
*Faircoin:_  fJU1XrPwymcwf6DuLrCBBAvsp9Bqg36znd

_-----BEGIN PGP PUBLIC KEY BLOCK-----_
Version: Mailvelope v1.1.0
Comment: https://www.mailvelope.com

xsFNBFYQUpABEADkkxRUWDjyeeWvPdgq5rjKNjvBhERSN8WPU79DKRfWWWss
UetyBOXGTffeC1WuCM2e6X3A2gxZGsp+gm/YcsiCY6SPS80ilInLbi9kBYAO
grWsDAbqArhXUoLJ/SaBq23ZX1hoJ4iliTTOeCkF1kKOA3ILa9SLeXjsCjQG
vuXgpRjdcf/c9Hy/aN1HZl4ln9KorlE8SUioJj7r4kjd99JbWWzKivGRjIFN
EeJm9xZvTUoQXwvNmVK0s3+SHN9Bb8b0lBJntndJkD4W8Y3n/CDc0WcW1m+I
gJYE7eIkrAJ1Req3sNA4uoZlwX+bW7hDIiVxkUhoqUGNfZ2n3PwRMU99uF+t
6k3YDRkOTFP1uxDSh3HCuE9nkUnkX1aFilbM22uQx72OFfIX3IET6rAFMKc4
nWaoGzUkqQ0S/mRPyMUrPtYKKyLx9igEvFsOoIDk4bmg+8EBsGXiwiFruU7A
xS35HRHQMGEKMdzqeY+x7kWzquE/JsqcXq1NXydc7A+7E0eKMJN5MzpPjfcl
kj9yWp9Tcc9jUiprnj3PyJ8imteG1tXoD71ZJjywKbYXgxgZBPXJSMmt/EX9
ye6AmSVqJk4Bf1eZwjF57ZY2HBRwQG2P699dMPgYbXhYOYjqJJ5QveLX3OVb
/jav5OA2DjS5Ui/uATMrEvNgHhDiMRYrmk7tiwARAQABzS5EaWVnbyBHb256
w6FsZXogUm9kcsOtZ3VleiA8eG11bmNoQHhtdW5jaC5jb20+wsF1BBABCAAp
BQJWEFKhBgsJCAcDAgkQDJxeBqNzk8EEFQgCCgMWAgECGQECGwMCHgEAAO8K
EADf4XqCntz9b7INAdvN8t/tKZC4mSxTTDFlSdMN3o3N5xe349vtfT6WWz7X
6M3CHBkkM2C2pTgl7tworQvXxytsLOSzJMN+pbzp4rtMwAyJsU1NxoXF+1P2
YrcFTKPAfa3umu+Uz0uw0Rkq9jRIcc6CcoxYsH6hBnViSqpyOvk4ni4+wlJA
zgskMNgPRjRY2AeX6cG8YzLlq0LUDP1V2M8ZGwg151FO4Be+/RpqbiTjngDz
vIJhC5Uxt0F4Ev1RxLx34B5bxZ8dtmCPTQKE6L2ZVYdjj/SveJWQm/8FY40d
pKsfvoaOh7uUud+vmGoiQ0ArkobTqhI2Yvv5H+MlFiUvF0ZsC2c4SMdGpKOS
j6GJ0Nozt2CoEKdsZbLJwUv3tmS1HvdcYaiVVpbVUUZslRnVPJtyWvh3QyPf
k4k7sseoYM6N/b72mUKwsPnMT2VQ/Dd9u/+77D/v2z18QWioZ9mKcWCA97C5
FXMW5/yB+S4qWzE5VOiO8TsfGN4eLViCrS5u7OpWElYzffH3ybBWse6gL/oI
r4AzaBxB7vxvqoMUE/AEFOC7rBgSEkzFQ+Fp2zOkaF2LK+9mTr6litulGoaJ
F+91utwvlSxvf/qPAABvId1KHT/8ZPpHRYX8ongSC8InXaFLAftAznoWRxnU
K11b0JyQWQKH1PsbRxXFBO4Dzs7BTQRWEFKQARAA6FAeF6xik02lg1oX5BUk
uHIPdeC0gFUVKp70kWxPqANEFFFjcmtciKSaUuEvMZWAo0PGwDJWJMB89SjK
wX8+ETdVhFZBoGGaJ4nsEe8TnDtBXrYcT/0sVvFqaU8rgLtQ670zl4Q2stSq
go31sJEILmwV4g4ui/71IoUaKwTOY4MMfU0g71ZEvrN87mulK9e2u8OPa5VA
8IKW28DPNNV2bB3iBPTeCsLM9s5hbU+eIHxy5X605CxylviunxA13qt/CilP
1IILk/p4PkcZkwnF1fF+Je2AcIZwL8kBMckvmWntYHn0iI69//7v4RJPa8De
6wQa11JcLoqdLoY1EjZ09COnezS5HjOiNKYbMG09zyRDbfOLWxmJJZ7sjtLn
J+OPCZXaXalDVPada+jHZ7JpwztnIO2oj8dfoofwboTAvbuiSxfMVxHJFDss
+hKQTPyNg8VrYfjJYPTV/q/vZb2p02eM6r5IcuXYh/aOGGA7UyChpE949Uwi
GMB8L1E+S5yIBKsRCqtqxsiG9GWJfSw4xqyutxqor0qzTdPy3EDqICxuZXDH
hpWJ/zbhPnIIVqkcpxeuFJBKdVUnKo2mEj9mGb/wFFD+jn6ioVj31NEHb+Jv
IHjPBT2TZyoMsHROTEtH92jbG81Suady64WH0QMHzfjD7TkBXOwlowNrMaSh
+dsAEQEAAcLBXwQYAQgAEwUCVhBSowkQDJxeBqNzk8ECGwwAAHr1EAChb2EG
NH5uclXmn/dsEcrGd+KUQq0CgFxu3sOI3kbbaBSDAjpF1vHgF1L75xu+Tz8Y
/jnvrWagNntko+c+PT/7GviKA0qXjis+3H57a8cmRmJ8Sl3QKcUMkXCYv/NE
NKc+RwlXi5kTsqDR7lt1caiy/7Pmw6ax9D1C2nsWDFdZ6jYM/t69zla2GIhw
OW9tqj60QyErgJjUqr5Z8MqtdXiS96hbQRbiRcwmFreAe54//uXdKNJFduvt
bk+3Q4maEnasnjZLLYaBSPN33XUWSFsm23DVXbyCrxtlNx9ka4I2qPutdkJv
/NU1do/1mxXHPpmkcrQjQ3B9u6Jw+8kfKxTbj3sd3ulIIqfBeSkQv5M24V0j
rpA3fhGWIFwED1KmyHy0FLIsS8epeDX8IKUoAZD2B4VVnzggea9dQ4dmXPQN
QrTXDQvOR4S8JW3w3PhsVS7fMRnxFYw6FxgpnVDN7tUJzKwno7+15Ql1uVHX
pXdsTvY+hmyjfTeowAcmzZ+6n+oLx5b9Ib7W+jFY4seetdlrhZD2uDboPdQ5
YU4z2P9pkfpqJYxS4CDHJf1bjLA2EkdgBVqQYTR3mocMzDxZ8K8cAfgtXK31
SOkJW2xFFmDASfZqW+IYS7TcCl/uHjBkIomKdCZCO1AdPHCl/wNWdGSZUQBF
t6j7X39i0c3o+8vexA==
=VpBM

_-----END PGP PUBLIC KEY BLOCK-----_

**Comment by dahacouk** [comment]
Thanks! Awesome!

**Comment by dahacouk** [comment]
Just to have a reference, this is how it should end up looking like:

![window_and_ovn_space___network_of_networks](https://cloud.githubusercontent.com/assets/201752/10709519/5c897312-7a29-11e5-90ee-52a9f8600850.png)

**Comment by dgrmunch** [comment]
Ey Daniel!

Task done! :-)

Looking forward to see your content in ovn.space.
I will consider your proposed changes in less than one month :-D

Best!

_Diego González Rodríguez_
Phone*: *(0034) 625899119
Email: xmunch@xmunch.com
Personal web: http://www.xmunch.com

_Bitcoin:_ 1JLg3M9H2xS4qbZEkRkvY8eeSDAVW1kho8
_Litecoin: \* LPRt76XYmvGK3i73z9dBYHBBnhTS656UTs
*Faircoin:_  fJU1XrPwymcwf6DuLrCBBAvsp9Bqg36znd

_-----BEGIN PGP PUBLIC KEY BLOCK-----_
Version: Mailvelope v1.1.0
Comment: https://www.mailvelope.com

xsFNBFYQUpABEADkkxRUWDjyeeWvPdgq5rjKNjvBhERSN8WPU79DKRfWWWss
UetyBOXGTffeC1WuCM2e6X3A2gxZGsp+gm/YcsiCY6SPS80ilInLbi9kBYAO
grWsDAbqArhXUoLJ/SaBq23ZX1hoJ4iliTTOeCkF1kKOA3ILa9SLeXjsCjQG
vuXgpRjdcf/c9Hy/aN1HZl4ln9KorlE8SUioJj7r4kjd99JbWWzKivGRjIFN
EeJm9xZvTUoQXwvNmVK0s3+SHN9Bb8b0lBJntndJkD4W8Y3n/CDc0WcW1m+I
gJYE7eIkrAJ1Req3sNA4uoZlwX+bW7hDIiVxkUhoqUGNfZ2n3PwRMU99uF+t
6k3YDRkOTFP1uxDSh3HCuE9nkUnkX1aFilbM22uQx72OFfIX3IET6rAFMKc4
nWaoGzUkqQ0S/mRPyMUrPtYKKyLx9igEvFsOoIDk4bmg+8EBsGXiwiFruU7A
xS35HRHQMGEKMdzqeY+x7kWzquE/JsqcXq1NXydc7A+7E0eKMJN5MzpPjfcl
kj9yWp9Tcc9jUiprnj3PyJ8imteG1tXoD71ZJjywKbYXgxgZBPXJSMmt/EX9
ye6AmSVqJk4Bf1eZwjF57ZY2HBRwQG2P699dMPgYbXhYOYjqJJ5QveLX3OVb
/jav5OA2DjS5Ui/uATMrEvNgHhDiMRYrmk7tiwARAQABzS5EaWVnbyBHb256
w6FsZXogUm9kcsOtZ3VleiA8eG11bmNoQHhtdW5jaC5jb20+wsF1BBABCAAp
BQJWEFKhBgsJCAcDAgkQDJxeBqNzk8EEFQgCCgMWAgECGQECGwMCHgEAAO8K
EADf4XqCntz9b7INAdvN8t/tKZC4mSxTTDFlSdMN3o3N5xe349vtfT6WWz7X
6M3CHBkkM2C2pTgl7tworQvXxytsLOSzJMN+pbzp4rtMwAyJsU1NxoXF+1P2
YrcFTKPAfa3umu+Uz0uw0Rkq9jRIcc6CcoxYsH6hBnViSqpyOvk4ni4+wlJA
zgskMNgPRjRY2AeX6cG8YzLlq0LUDP1V2M8ZGwg151FO4Be+/RpqbiTjngDz
vIJhC5Uxt0F4Ev1RxLx34B5bxZ8dtmCPTQKE6L2ZVYdjj/SveJWQm/8FY40d
pKsfvoaOh7uUud+vmGoiQ0ArkobTqhI2Yvv5H+MlFiUvF0ZsC2c4SMdGpKOS
j6GJ0Nozt2CoEKdsZbLJwUv3tmS1HvdcYaiVVpbVUUZslRnVPJtyWvh3QyPf
k4k7sseoYM6N/b72mUKwsPnMT2VQ/Dd9u/+77D/v2z18QWioZ9mKcWCA97C5
FXMW5/yB+S4qWzE5VOiO8TsfGN4eLViCrS5u7OpWElYzffH3ybBWse6gL/oI
r4AzaBxB7vxvqoMUE/AEFOC7rBgSEkzFQ+Fp2zOkaF2LK+9mTr6litulGoaJ
F+91utwvlSxvf/qPAABvId1KHT/8ZPpHRYX8ongSC8InXaFLAftAznoWRxnU
K11b0JyQWQKH1PsbRxXFBO4Dzs7BTQRWEFKQARAA6FAeF6xik02lg1oX5BUk
uHIPdeC0gFUVKp70kWxPqANEFFFjcmtciKSaUuEvMZWAo0PGwDJWJMB89SjK
wX8+ETdVhFZBoGGaJ4nsEe8TnDtBXrYcT/0sVvFqaU8rgLtQ670zl4Q2stSq
go31sJEILmwV4g4ui/71IoUaKwTOY4MMfU0g71ZEvrN87mulK9e2u8OPa5VA
8IKW28DPNNV2bB3iBPTeCsLM9s5hbU+eIHxy5X605CxylviunxA13qt/CilP
1IILk/p4PkcZkwnF1fF+Je2AcIZwL8kBMckvmWntYHn0iI69//7v4RJPa8De
6wQa11JcLoqdLoY1EjZ09COnezS5HjOiNKYbMG09zyRDbfOLWxmJJZ7sjtLn
J+OPCZXaXalDVPada+jHZ7JpwztnIO2oj8dfoofwboTAvbuiSxfMVxHJFDss
+hKQTPyNg8VrYfjJYPTV/q/vZb2p02eM6r5IcuXYh/aOGGA7UyChpE949Uwi
GMB8L1E+S5yIBKsRCqtqxsiG9GWJfSw4xqyutxqor0qzTdPy3EDqICxuZXDH
hpWJ/zbhPnIIVqkcpxeuFJBKdVUnKo2mEj9mGb/wFFD+jn6ioVj31NEHb+Jv
IHjPBT2TZyoMsHROTEtH92jbG81Suady64WH0QMHzfjD7TkBXOwlowNrMaSh
+dsAEQEAAcLBXwQYAQgAEwUCVhBSowkQDJxeBqNzk8ECGwwAAHr1EAChb2EG
NH5uclXmn/dsEcrGd+KUQq0CgFxu3sOI3kbbaBSDAjpF1vHgF1L75xu+Tz8Y
/jnvrWagNntko+c+PT/7GviKA0qXjis+3H57a8cmRmJ8Sl3QKcUMkXCYv/NE
NKc+RwlXi5kTsqDR7lt1caiy/7Pmw6ax9D1C2nsWDFdZ6jYM/t69zla2GIhw
OW9tqj60QyErgJjUqr5Z8MqtdXiS96hbQRbiRcwmFreAe54//uXdKNJFduvt
bk+3Q4maEnasnjZLLYaBSPN33XUWSFsm23DVXbyCrxtlNx9ka4I2qPutdkJv
/NU1do/1mxXHPpmkcrQjQ3B9u6Jw+8kfKxTbj3sd3ulIIqfBeSkQv5M24V0j
rpA3fhGWIFwED1KmyHy0FLIsS8epeDX8IKUoAZD2B4VVnzggea9dQ4dmXPQN
QrTXDQvOR4S8JW3w3PhsVS7fMRnxFYw6FxgpnVDN7tUJzKwno7+15Ql1uVHX
pXdsTvY+hmyjfTeowAcmzZ+6n+oLx5b9Ib7W+jFY4seetdlrhZD2uDboPdQ5
YU4z2P9pkfpqJYxS4CDHJf1bjLA2EkdgBVqQYTR3mocMzDxZ8K8cAfgtXK31
SOkJW2xFFmDASfZqW+IYS7TcCl/uHjBkIomKdCZCO1AdPHCl/wNWdGSZUQBF
t6j7X39i0c3o+8vexA==
=VpBM

_-----END PGP PUBLIC KEY BLOCK-----_

**Comment by dahacouk** [comment]
Thanks! It's a shame that the http://ovn.space/#team listing for Mikorizal has a very lowres logo http://mikorizal.org/mushy40.jpg – I'll contact https://github.com/bhaugen @bhaugen and https://github.com/fosterlynn @fosterlynn to see if they can update it with a better one.

**Comment by dahacouk** [comment]
Any reason Metamaps was removed? Just interested.

**Comment by dgrmunch** [comment]
Great!

On Saturday, 24 October 2015, Daniel Harris notifications@github.com
wrote:

> Thanks! It's a shame that the http://ovn.space/#team listing for
> Mikorizal has a very lowres logo http://mikorizal.org/mushy40.jpg – I'll
> contact https://github.com/bhaugen @bhaugen https://github.com/bhaugen
> and https://github.com/fosterlynn @fosterlynn
> https://github.com/fosterlynn to see if they can update it with a
> better one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bitmindco/ovn-space/issues/3#issuecomment-150803693.

## 

_Diego González Rodríguez_
Phone*: *(0034) 625899119
Email: xmunch@xmunch.com
Personal web: http://www.xmunch.com

_Bitcoin:_ 1JLg3M9H2xS4qbZEkRkvY8eeSDAVW1kho8
_Litecoin: \* LPRt76XYmvGK3i73z9dBYHBBnhTS656UTs
*Faircoin:_  fJU1XrPwymcwf6DuLrCBBAvsp9Bqg36znd

_-----BEGIN PGP PUBLIC KEY BLOCK-----_
Version: Mailvelope v1.1.0
Comment: https://www.mailvelope.com

xsFNBFYQUpABEADkkxRUWDjyeeWvPdgq5rjKNjvBhERSN8WPU79DKRfWWWss
UetyBOXGTffeC1WuCM2e6X3A2gxZGsp+gm/YcsiCY6SPS80ilInLbi9kBYAO
grWsDAbqArhXUoLJ/SaBq23ZX1hoJ4iliTTOeCkF1kKOA3ILa9SLeXjsCjQG
vuXgpRjdcf/c9Hy/aN1HZl4ln9KorlE8SUioJj7r4kjd99JbWWzKivGRjIFN
EeJm9xZvTUoQXwvNmVK0s3+SHN9Bb8b0lBJntndJkD4W8Y3n/CDc0WcW1m+I
gJYE7eIkrAJ1Req3sNA4uoZlwX+bW7hDIiVxkUhoqUGNfZ2n3PwRMU99uF+t
6k3YDRkOTFP1uxDSh3HCuE9nkUnkX1aFilbM22uQx72OFfIX3IET6rAFMKc4
nWaoGzUkqQ0S/mRPyMUrPtYKKyLx9igEvFsOoIDk4bmg+8EBsGXiwiFruU7A
xS35HRHQMGEKMdzqeY+x7kWzquE/JsqcXq1NXydc7A+7E0eKMJN5MzpPjfcl
kj9yWp9Tcc9jUiprnj3PyJ8imteG1tXoD71ZJjywKbYXgxgZBPXJSMmt/EX9
ye6AmSVqJk4Bf1eZwjF57ZY2HBRwQG2P699dMPgYbXhYOYjqJJ5QveLX3OVb
/jav5OA2DjS5Ui/uATMrEvNgHhDiMRYrmk7tiwARAQABzS5EaWVnbyBHb256
w6FsZXogUm9kcsOtZ3VleiA8eG11bmNoQHhtdW5jaC5jb20+wsF1BBABCAAp
BQJWEFKhBgsJCAcDAgkQDJxeBqNzk8EEFQgCCgMWAgECGQECGwMCHgEAAO8K
EADf4XqCntz9b7INAdvN8t/tKZC4mSxTTDFlSdMN3o3N5xe349vtfT6WWz7X
6M3CHBkkM2C2pTgl7tworQvXxytsLOSzJMN+pbzp4rtMwAyJsU1NxoXF+1P2
YrcFTKPAfa3umu+Uz0uw0Rkq9jRIcc6CcoxYsH6hBnViSqpyOvk4ni4+wlJA
zgskMNgPRjRY2AeX6cG8YzLlq0LUDP1V2M8ZGwg151FO4Be+/RpqbiTjngDz
vIJhC5Uxt0F4Ev1RxLx34B5bxZ8dtmCPTQKE6L2ZVYdjj/SveJWQm/8FY40d
pKsfvoaOh7uUud+vmGoiQ0ArkobTqhI2Yvv5H+MlFiUvF0ZsC2c4SMdGpKOS
j6GJ0Nozt2CoEKdsZbLJwUv3tmS1HvdcYaiVVpbVUUZslRnVPJtyWvh3QyPf
k4k7sseoYM6N/b72mUKwsPnMT2VQ/Dd9u/+77D/v2z18QWioZ9mKcWCA97C5
FXMW5/yB+S4qWzE5VOiO8TsfGN4eLViCrS5u7OpWElYzffH3ybBWse6gL/oI
r4AzaBxB7vxvqoMUE/AEFOC7rBgSEkzFQ+Fp2zOkaF2LK+9mTr6litulGoaJ
F+91utwvlSxvf/qPAABvId1KHT/8ZPpHRYX8ongSC8InXaFLAftAznoWRxnU
K11b0JyQWQKH1PsbRxXFBO4Dzs7BTQRWEFKQARAA6FAeF6xik02lg1oX5BUk
uHIPdeC0gFUVKp70kWxPqANEFFFjcmtciKSaUuEvMZWAo0PGwDJWJMB89SjK
wX8+ETdVhFZBoGGaJ4nsEe8TnDtBXrYcT/0sVvFqaU8rgLtQ670zl4Q2stSq
go31sJEILmwV4g4ui/71IoUaKwTOY4MMfU0g71ZEvrN87mulK9e2u8OPa5VA
8IKW28DPNNV2bB3iBPTeCsLM9s5hbU+eIHxy5X605CxylviunxA13qt/CilP
1IILk/p4PkcZkwnF1fF+Je2AcIZwL8kBMckvmWntYHn0iI69//7v4RJPa8De
6wQa11JcLoqdLoY1EjZ09COnezS5HjOiNKYbMG09zyRDbfOLWxmJJZ7sjtLn
J+OPCZXaXalDVPada+jHZ7JpwztnIO2oj8dfoofwboTAvbuiSxfMVxHJFDss
+hKQTPyNg8VrYfjJYPTV/q/vZb2p02eM6r5IcuXYh/aOGGA7UyChpE949Uwi
GMB8L1E+S5yIBKsRCqtqxsiG9GWJfSw4xqyutxqor0qzTdPy3EDqICxuZXDH
hpWJ/zbhPnIIVqkcpxeuFJBKdVUnKo2mEj9mGb/wFFD+jn6ioVj31NEHb+Jv
IHjPBT2TZyoMsHROTEtH92jbG81Suady64WH0QMHzfjD7TkBXOwlowNrMaSh
+dsAEQEAAcLBXwQYAQgAEwUCVhBSowkQDJxeBqNzk8ECGwwAAHr1EAChb2EG
NH5uclXmn/dsEcrGd+KUQq0CgFxu3sOI3kbbaBSDAjpF1vHgF1L75xu+Tz8Y
/jnvrWagNntko+c+PT/7GviKA0qXjis+3H57a8cmRmJ8Sl3QKcUMkXCYv/NE
NKc+RwlXi5kTsqDR7lt1caiy/7Pmw6ax9D1C2nsWDFdZ6jYM/t69zla2GIhw
OW9tqj60QyErgJjUqr5Z8MqtdXiS96hbQRbiRcwmFreAe54//uXdKNJFduvt
bk+3Q4maEnasnjZLLYaBSPN33XUWSFsm23DVXbyCrxtlNx9ka4I2qPutdkJv
/NU1do/1mxXHPpmkcrQjQ3B9u6Jw+8kfKxTbj3sd3ulIIqfBeSkQv5M24V0j
rpA3fhGWIFwED1KmyHy0FLIsS8epeDX8IKUoAZD2B4VVnzggea9dQ4dmXPQN
QrTXDQvOR4S8JW3w3PhsVS7fMRnxFYw6FxgpnVDN7tUJzKwno7+15Ql1uVHX
pXdsTvY+hmyjfTeowAcmzZ+6n+oLx5b9Ib7W+jFY4seetdlrhZD2uDboPdQ5
YU4z2P9pkfpqJYxS4CDHJf1bjLA2EkdgBVqQYTR3mocMzDxZ8K8cAfgtXK31
SOkJW2xFFmDASfZqW+IYS7TcCl/uHjBkIomKdCZCO1AdPHCl/wNWdGSZUQBF
t6j7X39i0c3o+8vexA==
=VpBM

_-----END PGP PUBLIC KEY BLOCK-----_

**Comment by dgrmunch** [comment]
Ups! Yes! I have to add it again. Somehow the Metamaps
div disappeared while I was adding the new ones. Again, doing things fast
is not fine :-)
I'll put it back in a couple of weeks. And I will also add some others
nodes of the network. I have to talk again with the people of Backfeed too.
Unfortunatelly, since the summer I have been delaying some pending issues
in the site because some priorities. But everything will be updated then.
Meanwhile, you can start to improve the content of the site publishing in
the news or documents sections.

Best and thanks

On Saturday, 24 October 2015, Daniel Harris notifications@github.com
wrote:

> Any reason Metamaps was removed? Just interested.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bitmindco/ovn-space/issues/3#issuecomment-150803985.

## 

_Diego González Rodríguez_
Phone*: *(0034) 625899119
Email: xmunch@xmunch.com
Personal web: http://www.xmunch.com

_Bitcoin:_ 1JLg3M9H2xS4qbZEkRkvY8eeSDAVW1kho8
_Litecoin: \* LPRt76XYmvGK3i73z9dBYHBBnhTS656UTs
*Faircoin:_  fJU1XrPwymcwf6DuLrCBBAvsp9Bqg36znd

_-----BEGIN PGP PUBLIC KEY BLOCK-----_
Version: Mailvelope v1.1.0
Comment: https://www.mailvelope.com

xsFNBFYQUpABEADkkxRUWDjyeeWvPdgq5rjKNjvBhERSN8WPU79DKRfWWWss
UetyBOXGTffeC1WuCM2e6X3A2gxZGsp+gm/YcsiCY6SPS80ilInLbi9kBYAO
grWsDAbqArhXUoLJ/SaBq23ZX1hoJ4iliTTOeCkF1kKOA3ILa9SLeXjsCjQG
vuXgpRjdcf/c9Hy/aN1HZl4ln9KorlE8SUioJj7r4kjd99JbWWzKivGRjIFN
EeJm9xZvTUoQXwvNmVK0s3+SHN9Bb8b0lBJntndJkD4W8Y3n/CDc0WcW1m+I
gJYE7eIkrAJ1Req3sNA4uoZlwX+bW7hDIiVxkUhoqUGNfZ2n3PwRMU99uF+t
6k3YDRkOTFP1uxDSh3HCuE9nkUnkX1aFilbM22uQx72OFfIX3IET6rAFMKc4
nWaoGzUkqQ0S/mRPyMUrPtYKKyLx9igEvFsOoIDk4bmg+8EBsGXiwiFruU7A
xS35HRHQMGEKMdzqeY+x7kWzquE/JsqcXq1NXydc7A+7E0eKMJN5MzpPjfcl
kj9yWp9Tcc9jUiprnj3PyJ8imteG1tXoD71ZJjywKbYXgxgZBPXJSMmt/EX9
ye6AmSVqJk4Bf1eZwjF57ZY2HBRwQG2P699dMPgYbXhYOYjqJJ5QveLX3OVb
/jav5OA2DjS5Ui/uATMrEvNgHhDiMRYrmk7tiwARAQABzS5EaWVnbyBHb256
w6FsZXogUm9kcsOtZ3VleiA8eG11bmNoQHhtdW5jaC5jb20+wsF1BBABCAAp
BQJWEFKhBgsJCAcDAgkQDJxeBqNzk8EEFQgCCgMWAgECGQECGwMCHgEAAO8K
EADf4XqCntz9b7INAdvN8t/tKZC4mSxTTDFlSdMN3o3N5xe349vtfT6WWz7X
6M3CHBkkM2C2pTgl7tworQvXxytsLOSzJMN+pbzp4rtMwAyJsU1NxoXF+1P2
YrcFTKPAfa3umu+Uz0uw0Rkq9jRIcc6CcoxYsH6hBnViSqpyOvk4ni4+wlJA
zgskMNgPRjRY2AeX6cG8YzLlq0LUDP1V2M8ZGwg151FO4Be+/RpqbiTjngDz
vIJhC5Uxt0F4Ev1RxLx34B5bxZ8dtmCPTQKE6L2ZVYdjj/SveJWQm/8FY40d
pKsfvoaOh7uUud+vmGoiQ0ArkobTqhI2Yvv5H+MlFiUvF0ZsC2c4SMdGpKOS
j6GJ0Nozt2CoEKdsZbLJwUv3tmS1HvdcYaiVVpbVUUZslRnVPJtyWvh3QyPf
k4k7sseoYM6N/b72mUKwsPnMT2VQ/Dd9u/+77D/v2z18QWioZ9mKcWCA97C5
FXMW5/yB+S4qWzE5VOiO8TsfGN4eLViCrS5u7OpWElYzffH3ybBWse6gL/oI
r4AzaBxB7vxvqoMUE/AEFOC7rBgSEkzFQ+Fp2zOkaF2LK+9mTr6litulGoaJ
F+91utwvlSxvf/qPAABvId1KHT/8ZPpHRYX8ongSC8InXaFLAftAznoWRxnU
K11b0JyQWQKH1PsbRxXFBO4Dzs7BTQRWEFKQARAA6FAeF6xik02lg1oX5BUk
uHIPdeC0gFUVKp70kWxPqANEFFFjcmtciKSaUuEvMZWAo0PGwDJWJMB89SjK
wX8+ETdVhFZBoGGaJ4nsEe8TnDtBXrYcT/0sVvFqaU8rgLtQ670zl4Q2stSq
go31sJEILmwV4g4ui/71IoUaKwTOY4MMfU0g71ZEvrN87mulK9e2u8OPa5VA
8IKW28DPNNV2bB3iBPTeCsLM9s5hbU+eIHxy5X605CxylviunxA13qt/CilP
1IILk/p4PkcZkwnF1fF+Je2AcIZwL8kBMckvmWntYHn0iI69//7v4RJPa8De
6wQa11JcLoqdLoY1EjZ09COnezS5HjOiNKYbMG09zyRDbfOLWxmJJZ7sjtLn
J+OPCZXaXalDVPada+jHZ7JpwztnIO2oj8dfoofwboTAvbuiSxfMVxHJFDss
+hKQTPyNg8VrYfjJYPTV/q/vZb2p02eM6r5IcuXYh/aOGGA7UyChpE949Uwi
GMB8L1E+S5yIBKsRCqtqxsiG9GWJfSw4xqyutxqor0qzTdPy3EDqICxuZXDH
hpWJ/zbhPnIIVqkcpxeuFJBKdVUnKo2mEj9mGb/wFFD+jn6ioVj31NEHb+Jv
IHjPBT2TZyoMsHROTEtH92jbG81Suady64WH0QMHzfjD7TkBXOwlowNrMaSh
+dsAEQEAAcLBXwQYAQgAEwUCVhBSowkQDJxeBqNzk8ECGwwAAHr1EAChb2EG
NH5uclXmn/dsEcrGd+KUQq0CgFxu3sOI3kbbaBSDAjpF1vHgF1L75xu+Tz8Y
/jnvrWagNntko+c+PT/7GviKA0qXjis+3H57a8cmRmJ8Sl3QKcUMkXCYv/NE
NKc+RwlXi5kTsqDR7lt1caiy/7Pmw6ax9D1C2nsWDFdZ6jYM/t69zla2GIhw
OW9tqj60QyErgJjUqr5Z8MqtdXiS96hbQRbiRcwmFreAe54//uXdKNJFduvt
bk+3Q4maEnasnjZLLYaBSPN33XUWSFsm23DVXbyCrxtlNx9ka4I2qPutdkJv
/NU1do/1mxXHPpmkcrQjQ3B9u6Jw+8kfKxTbj3sd3ulIIqfBeSkQv5M24V0j
rpA3fhGWIFwED1KmyHy0FLIsS8epeDX8IKUoAZD2B4VVnzggea9dQ4dmXPQN
QrTXDQvOR4S8JW3w3PhsVS7fMRnxFYw6FxgpnVDN7tUJzKwno7+15Ql1uVHX
pXdsTvY+hmyjfTeowAcmzZ+6n+oLx5b9Ib7W+jFY4seetdlrhZD2uDboPdQ5
YU4z2P9pkfpqJYxS4CDHJf1bjLA2EkdgBVqQYTR3mocMzDxZ8K8cAfgtXK31
SOkJW2xFFmDASfZqW+IYS7TcCl/uHjBkIomKdCZCO1AdPHCl/wNWdGSZUQBF
t6j7X39i0c3o+8vexA==
=VpBM

_-----END PGP PUBLIC KEY BLOCK-----_

**Comment by fosterlynn** [comment]
@dahacouk  Thanks for catching the lousy logo, what we provided @dgrmunch probably didn't fit that format too well, and also started out a bit rough.  We don't have much in the way of "branding" for mikorizal, just hasn't been a priority for us.  (We are not part of the "branding" age or mindset.)

However, I will take a bit of time to try to make something that will fit into that space.  Won't be a big mushroom, that is the only version we have of that, got it off the web a while back. :)  But I'll come up with something that will fit into the space....

**Comment by dgrmunch** [comment]
Do not worry @fosterlynn, I will add soon the new logo you sent me. I am gonna open a couple of issues in this repo, just in order to remember it.
